
const translation={
    english:{
        KualaTilte:" Kuala Lumpur",
        Airport_Layover:"Kuala Lumpur Airport Layover Leisure Trip",
        ViewMore:"View More",
        LeisureTrip:"Leisure Trip on Wednesday (6 hours)",
        Seremban :"Seremban + Port Dickson + Putrajaya 1 Day Trip",
        Ticket_Free:"Kuala Lumpur Ticket-Free Attractions",
        PUTRAJAYA :"PUTRAJAYA + MALACCA 1 Day Trip",
        StudyAbroad:"Kuala Lumpur Study Abroad Consultation + Educational Enrollment Agency Program Vehicle Rental",
        PenangHouse:"Kuala Lumpur / Penang House and Vehicle Rentals + Nanny and Security Services",
        Health:"Kuala Lumpur Comprehensive Health Examination Center + Multilingual Training Center + Student Talent Development Center",
        About:"About",
        aboutbold:"Us",
        abouttext:"At PRO TEAM HOLIDAY SDN BHD, we are passionate about transforming ordinary journeys into extraordinary adventures. Our mission is to provide you with seamless travel experiences that can save our customers time but can create lasting memories. We take the stress out of planning and let you focus on the joy of exploring the world. Our dedicated team of travel experts works tirelessly to curate seamless travel packages that cater to your unique preferences,interests, and desires.",
        Kualapagetitle:" Kuala Lumpur Airport Layover Leisure Trip",
        Thai:'Thai Massage Palace: (One-hour full-body massage MYR 66, one-hour foot massage MYR 50) Self-pay* 1-day advance reservation, 11 am to 10 pm',
        Nail:'Nail Services: Starting from MYR 48, self-pay',
        hair:"Hair Services: Starting from MYR 30, self-pay",
        Shopping:"Shopping",
        Cuisine:"Malaysian Cuisine: Banana Pancakes, ROTI TISSUE, Teh Tarik, and more.",
        Term:"Term and Condition:",
        Timing: "Timing and itinerary may be subject to change based on circumstances.",
        removeitems: "You can add or remove items from the itinerary at your discretion.",
        Prices: "Prices will vary based on changes to the itinerary.",
        Cancellations:"Cancellations made at least 24 hours in advance will receive a full refund.",
        reservation:"If a reservation is cancelled within 24 hours, the deposit will not be refunded but will be retained for a future booking.",
        Photography:"Photography services require a reservation at least 2 months in advance.",
        Extra:"Extra cost 30% from Chinese New Year’s Eve to the fifth day of the Chinese New Year.",
        Wednesday:" Leisure Trip on Wednesday (6 hours)",
        Depart:"5:00 PM: Depart from the KL area to Putrajaya (Visit the Pink Mosque- Masjid Putra).",
        Chinatown:"6:00 PM: Explore the Chinatown Food Street (Self-pay).",
        NightMarket:"8:00 PM: Discover Kuala Lumpur's Longest Night Market (Self-pay).",
        Endtrip:"9:45 PM: End of the trip.",
        Seremban:" Seremban + Port Dickson + Putrajaya 1 Day Trip",
        Pick_up:"KL Area Hotel Pick-up/Drop-off.",
        local_food:"Explore Seremban famous local food (Fu Rong Shao Bao [Fried Buns], Satay [Pork, Chicken, Lamb, and Pork Intestine], Cendol Kacang, Abc HSC [Ice Kacang], Yee Poh Lao Shu Fen)",
        DicksonBeach:"Visit Port Dickson Beach.",
        OutletKLIA:"Explore Premium Outlet KLIA.",
        Putrajaya:"Visit Putrajaya Masjid.",
        DurianFeast:"Durian Feast (Self-pay).",
        Returnhotel:"Return to the hotel to end the trip.",
        TicketFreetitle:"Kuala Lumpur Ticket-Free Attractions",
        BatuCaves:"Batu Caves",
        KingPalace:"King's Palace (Istana Negara)",
        KLCC:"KLCC Twin Towers (Petronas Towers)",
        Independence:"Independence Square (Dataran Merdeka)",
        Thean:"Thean Hou Temple",
        Chinatown:"Chinatown (Petaling Street)",
        Hong:"Kwai Chai Hong",
        MasjidJamek:"Masjid Jamek (River of Life)",
        RoyalSelangor:"Royal Selangor Visitor Center (1885)",
        PutraMosque:"Putrajaya Pink Mosque (Putra Mosque)",
        China_Malaysia:"China-Malaysia Friendship Garden",
        maintitlePUTRAJAYA:"PUTRAJAYA + MALACCA 1 Day Trip",
        postDepart:"Depart at 8:00 AM, Return at 4:00 PM or Depart at 12:00 PM, Return at 8:00 PM",
        PinkMosque:"1: Putrajaya, Pink Mosque (Putra Mosque), Malaysian Prime Minister's Office, China-Malaysia Friendship Garden.",
        RedHouse:"2: The Red House (Stadthuys), St. Paul's Hill, Jonker Street.",
        ChengHoon:"3: Cheng Hoon Teng Temple (The oldest surviving Chinese temple in Malaysia, renowned for its ornate decorations, Chinese sculptures, ceramic sculptures on the roof, and golden artwork on the temple doors. This is one of the many noteworthy buildings in Melaka.)",
        MelakaRiverbank:"4: Melaka Riverbank Walk.",
        Straits:"5: Straits Mosque (Masjid Selat Melaka).",
        Portuguese:"6: The 16th-century Portuguese fortress, A Famosa.",
        PrivateCharter:"Private Charter for Independent Travel:",
        PersonSmall:"4-Person Small Car: MYR 499.00",
        PersonMedium:"6-Person Medium Car: MYR 599.00",
        PersonBusiness:"6-Person Business Car: MYR 899.00",
        PersonLuxury:"5-Person Luxury Business Car: MYR 1299.00",
        StudyAbroad:"  Kuala Lumpur Study Abroad Consultation + Educational Enrollment Agency Program Vehicle Rental",
        Option1:"Option 1: School Visits Service (2 Schools/Day)",
        Fulltranslation:"Full translation",
        privatecar:"private car transportation",
        schoolappointment:"school appointment scheduling",
        translation:"translation of documents",
        Option2:"Option 2: Application Services",
        TranslateApplication:"Translate Application Materials",
        FullGuidance:"Provide Full Guidance On The Application Process",
        Assistvisa:"Assist With Visa Processing",
        Arrange:"Arrange Interviews",
        Accompanying:"Provide Accompanying Consultations",
        Selecting:"Assist In Selecting Study Options",
        FlexibleTiming:"Flexible Timing (min 5 hours)",
        Person4:"4-Person Small Car: MYR 48 per hours",
        Person6:"6-Person Medium Car: MYR 68 per hours",
        Person6_Business:"6-Person Business Car: MYR 88 per hours",
        Person6_Luxury:"5-Person Luxury Business Car: MYR 118 per hours",
        PenangHouse:" Kuala Lumpur / Penang House and Vehicle Rentals + Nanny and Security Services",
        VehicleRentals:"House and Vehicle Rentals",
        VehicleSelection:"Property (Vehicle) Selection",
        VehicleViewing:"Accompanied Property (Vehicle) Viewing",
        LeaseContract:"Lease Contract Translation",
        LegalConsultation:"Legal Consultation",
        SecurityService:"Add On: Nanny and Security Services",
        Comprehensive:"Kuala Lumpur Comprehensive Health Examination Center + Multilingual Training Center + Student Talent Development Center",
        Comprehensiveoption1:"Option 1: Comprehensive Health Examination Center",
        VariousHealth:"Various Health Examination Packages",
        ProfessionalTesting:"Professional Testing Equipment",
        MedicalExpert:"Medical Expert Report Analysis",
        Complimentary:"Complimentary Meals during Examination",
        Multilingualoption2:"Option 2: Multilingual Training Center",
        ForeignLanguage:"Experienced Foreign Language Instructors",
        ImmersiveLanguage:"Immersive Language Learning",
        LanguageSkills:"Comprehensive Language Skills Training",
        StudentTalent:"Option 3: Student Talent Development",
        TeachingTeam:"Professional Teaching Team",
        DiverseTalent:"Diverse Talent Development Program",
        VariousPerformance:"Various Performance Activities",
    
    
    
    
    
    
    
    
    
    },
    chineese:{
        KualaTilte:"吉隆坡",
        Airport_Layover: "吉隆坡机场中转休闲之旅",
        ViewMore:"查看更多",
        LeisureTrip :"周三休闲之旅（6小时）",
        Seremban:"芙蓉 + 波德申 + 布城 1 日游",
        Ticket_Free:"吉隆坡免票景点",
        PUTRAJAYA:"布城 + 马六甲 1 日游",
        StudyAbroad:"吉隆坡留学咨询+教育招生机构计划车辆租赁",
        PenangHouse:"吉隆坡/槟城房屋和车辆租赁+保姆和保安服务",
        Health:"吉隆坡综合健康检查中心+多语种培训中心+学生才艺发展中心",
        About:"关于",
        aboutbold:"我们",
        abouttext:"在 PRO TEAM HOLIDAY SDN BHD，我们热衷于将平凡的旅程转变为非凡的冒险。我们的使命是为您提供无缝的旅行体验，不仅可以节省客户的时间，还可以创造持久的回忆。我们消除了规划的压力，让您专注于探索世界的乐趣。我们的专业旅行专家团队孜孜不倦地努力策划无缝旅行套餐，以满足您独特的喜好、兴趣和愿望。",
        Kualapagetitle:"吉隆坡机场中转休闲之旅",
        Thai:"泰式按摩宫：（一小时全身按摩MYR 66，一小时足底按摩MYR 50）自费*提前1天预订，上午11点至晚上10点",
        Nail:'美甲服务：48马币起，自费”',
        hair:"美发服务：MYR 30 起，自费",
        Shopping:"购物",
        Cuisine:"马来西亚美食：香蕉煎饼、ROTI TISSUE、拉茶等。",
        Term:"规则与条例：",
        Timing:"时间和行程可能会根据情况发生变化。",
        removeitems: "您可以自行决定在行程中添加或删除项目。",
        Prices:"价格会根据行程的变化而有所不同。",
        Cancellations:"至少提前 24 小时取消将获得全额退款。",
        reservation:"如果在 24 小时内取消预订，押金将不予退还，但将保留以供将来预订使用。",
        Photography:"摄影服务需要至少提前2个月预约。",
        Extra:"除夕至初五加收30%费用。",
        Wednesday:"周三休闲之旅（6小时）",
        Depart:"5:00 PM：从吉隆坡地区出发前往布城（参观粉红清真寺-Masjid Putra）。",
        Chinatown:"6:00 PM：探索唐人街美食街（自费）。",
        NightMarket:"8:00 PM：探索吉隆坡最长的夜市（自费）。",
        Endtrip:"晚上9点45分：行程结束。",
        Seremban:"芙蓉 + 波德申 + 布城 1 日游",
        Pick_up:"吉隆坡地区酒店接送服务。",
        local_food:"探索芙蓉当地著名美食（芙蓉烧包 [炸包]、沙爹 [猪肉、鸡肉、羊肉和猪大肠]、Cendol Kacang、Abc HSC [红豆冰]、伊婆老树粉）",
        DicksonBeach:"游览波德申海滩。",
        OutletKLIA:"探索吉隆坡国际机场名品折扣店。",
        Putrajaya:"参观布城清真寺",
        DurianFeast:"榴莲宴（自费）",
        Returnhotel:"返回酒店结束行程",
        TicketFreetitle:"吉隆坡免票景点",
        BatuCaves:"黑风洞",
        KingPalace:"国家皇宫（Istana Negara）",
        KLCC:"KLCC 双子塔（双子塔）",
        Independence:"独立广场（Dataran Merdeka）",
        Thean:"天后宫",
        Chinatown:"唐人街（茨厂街",
        Hong:"葵柴行",
        MasjidJamek:"占美清真寺（生命之河）",
        RoyalSelangor:"皇家雪兰莪游客中心 (1885)",
        PutraMosque:"布城粉红清真寺（布特拉清真寺）",
        China_Malaysia:"中马友谊花园",
        maintitlePUTRAJAYA:"布城 + 马六甲 1 日游",
        postDepart:"上午 8:00 出发，下午 4:00 返回 或 中午 12:00 出发，晚上 8:00 返回",
        PinkMosque:"1：布城、粉红清真寺（Putra Mosque）、马来西亚总理府、中马友谊花园。",
        RedHouse:"2：红房子（Stadthuys）、圣保罗山、鸡场街。",
        ChengHoon:"3：青云亭（马来西亚现存最古老的华人寺庙，以其华丽的装饰、中国雕塑、屋顶上的陶瓷雕塑和寺庙门上的金色艺术品而闻名。这是马六甲众多值得注意的建筑之一。）",
        MelakaRiverbank:"4：马六甲河岸步道。",
        Straits:"5：海峡清真寺（Masjid Selat Melaka）。",
        Portuguese:"6：16 世纪的葡萄牙堡垒爱化摩沙城堡。",
        PrivateCharter:"自由行私人包车：",
        PersonSmall:"4人小型车：MYR 499.00",
        PersonMedium:"6 人中型车：MYR 599.00",
        PersonBusiness:"6人商务车：MYR 899.00",
        PersonLuxury:"5人豪华商务车：MYR 1299.00",
        StudyAbroad:"吉隆坡留学咨询+教育招生机构计划车辆租赁",
        Option1:"选项 1：学校参观服务（2 所学校/天）",
        Fulltranslation:"完整翻译",
        privatecar:"私家车交通",
        schoolappointment:"学校预约安排",
        translation:"文件翻译",
        Option2:"选项 2：应用程序服务",
        TranslateApplication:"翻译申请材料",
        FullGuidance:"提供申请流程的全面指导",
        Assistvisa:"协助签证处理",
        Arrange:"安排面试",
        Accompanying:"提供陪同咨询",
        Selecting:"协助选择学习选项",
        FlexibleTiming:"灵活的时间（最少 5 小时）",
        Person4:"4 人小型车：每小时 MYR 48",
        Person6:"6 人中型车：每小时 MYR 68",
        Person6_Business:"6人商务车：每小时 MYR 88",
        Person6_Luxury:"5人豪华商务车：每小时 MYR 118",
        PenangHouse:"吉隆坡/槟城房屋和车辆租赁+保姆和保安服务",
        VehicleRentals:"房屋和车辆租赁",
        VehicleSelection:"财产（车辆）选择",
        VehicleViewing:"陪同财产（车辆）查看",
        LeaseContract:"租赁合同翻译",
        LegalConsultation:"法律咨询",
        SecurityService:"附加：保姆和保安服务",
        Comprehensive:'吉隆坡综合健康检查中心+多语种培训中心+学生才艺发展中心',
        Comprehensiveoption1:"选择一：综合健康检查中心",
        VariousHealth:"各类健康检查套餐",
        ProfessionalTesting:"专业检测设备",
        MedicalExpert:"医学专家报告分析",
        Complimentary:'考试期间免费用餐',
        Multilingualoption2:"选项2：多语言培训中心",
        ForeignLanguage:"经验丰富的外语教师",
        ImmersiveLanguage:"沉浸式语言学习",
        LanguageSkills:"综合语言技能培训",
        StudentTalent:"选项 3：学生才能发展",
        TeachingTeam:"专业的教学团队",
        DiverseTalent:"多元化人才发展计划",
        VariousPerformance:"各类表演活动",




    }
}
const setLanguage=(lang)=>{
   
    const elements = document.querySelectorAll('[data-i18n]')
    // console.log(elements)
    elements.forEach((ele)=>{
      
        const translationKey=ele.getAttribute('data-i18n')
        // console.log(translationKey)
        // console.log(translation[lang][translationKey])
        ele.textContent=translation[lang][translationKey]
    })

}
setLanguage("chineese")
const getLang=localStorage.getItem("lang")
console.log(getLang)
setLanguage(getLang)
if(localStorage.getItem("lang")=="english"){
  
    window.top.document.title ="Malaysoa travel made easy"
  }
  else{
    window.top.document.title = "马来西亚旅行变得轻松"
    console.log("hel")
  }